Speciality.create(name: "Акушер")
Speciality.create(name: "Акушер-гинеколог")
Speciality.create(name: "Аллерголог")
Speciality.create(name: "Анестезиолог-реаниматолог")
Speciality.create(name: "Андролог")
Speciality.create(name: "Военно-полевой хирург")
Speciality.create(name: "Врач скорой помощи")
Speciality.create(name: "Врач УЗ-диагностики")
Speciality.create(name: "Врач МСЭК(медико-социальной экспертизы)")
Speciality.create(name: "Врач функциональной диагностики")
Speciality.create(name: "Гастроэнтеролог")
Speciality.create(name: "Гирудотерапевт")
Speciality.create(name: "Генетик")
Speciality.create(name: "Гепатолог")
Speciality.create(name: "Гомеопат")
Speciality.create(name: "Гематолог")
Speciality.create(name: "Гинеколог")
Speciality.create(name: "Дерматолог")
Speciality.create(name: "Диетолог")
Speciality.create(name: "Инфекционист")
Speciality.create(name: "Иммунолог")
Speciality.create(name: "Кардиолог")
Speciality.create(name: "Кардиохирург")
Speciality.create(name: "Косметолог")
Speciality.create(name: "Лаборант")
Speciality.create(name: "Лимфолог")
Speciality.create(name: "Логопед")
Speciality.create(name: "Мануалист")
Speciality.create(name: "Массажист")
Speciality.create(name: "Маммолог")
Speciality.create(name: "Медицинская сестра")
Speciality.create(name: "Нарколог")
Speciality.create(name: "Невролог")
Speciality.create(name: "Невропатолог")
Speciality.create(name: "Неонатолог")
Speciality.create(name: "Нейрохирург")
Speciality.create(name: "Нефролог")
Speciality.create(name: "Онколог")
Speciality.create(name: "Ортодонт")
Speciality.create(name: "Ортопед")
Speciality.create(name: "Оториноларинголог (ЛОР)")
Speciality.create(name: "Офтальмолог")
Speciality.create(name: "Патологоанатом")
Speciality.create(name: "Педиатр")
Speciality.create(name: "Пластический хирург")
Speciality.create(name: "Прозектор")
Speciality.create(name: "Проктолог")
Speciality.create(name: "Профпатолог")
Speciality.create(name: "Психиатр")
Speciality.create(name: "Психоневропатолог")
Speciality.create(name: "Психотерапевт")
Speciality.create(name: "Пульмонолог")
Speciality.create(name: "Радиолог")
Speciality.create(name: "Реаниматолог")
Speciality.create(name: "Ревматолог")
Speciality.create(name: "Рентгенолог")
Speciality.create(name: "Рефлексотерапевт")
Speciality.create(name: "Санитар")
Speciality.create(name: "Сексолог")
Speciality.create(name: "Сексопатолог")
Speciality.create(name: "Семейный врач")
Speciality.create(name: "Специалист по клеточным технологиям")
Speciality.create(name: "Спортивный врач")
Speciality.create(name: "Сомнолог")
Speciality.create(name: "Стоматолог")
Speciality.create(name: "Сурдолог")
Speciality.create(name: "Танатолог")
Speciality.create(name: "Терапевт")
Speciality.create(name: "Торакальный хирург")
Speciality.create(name: "Травматолог")
Speciality.create(name: "Трансфузиолог")
Speciality.create(name: "Токсиколог")
Speciality.create(name: "Фармацевт")
Speciality.create(name: "Фельдшер")
Speciality.create(name: "Физиотерапевт")
Speciality.create(name: "Флеболог")
Speciality.create(name: "Фтизиатр")
Speciality.create(name: "Хирург")
Speciality.create(name: "Уролог")
Speciality.create(name: "Эндокринолог")
Speciality.create(name: "Эндоскопист")
Speciality.create(name: "Эпидемиолог")
Speciality.create(name: "Эфферентолог")
